version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: northwind-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: northwind
      MYSQL_USER: northwind_user
      MYSQL_PASSWORD: northwind_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./northwind.sql:/docker-entrypoint-initdb.d/01-northwind.sql
      - ./northwind-data.sql:/docker-entrypoint-initdb.d/02-northwind-data.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 